version: '3'

services: 
  selenium:
    image: selenium/standalone-firefox
    ports: 
     - 4444:4444
    restart: always

  app:
    build: 
    # will use the dockerfile in current folder
      context: .
    # create a volume to link /app folder in container and /app folder in host 
    volumes: 
     - ./app:/app
    command: sh -c "python3 bot.py"
    depends_on: 
     - selenium